/**
 * Generates Cursor rules (.cursor/rules/*.mdc) from Claude Code rules (.claude/rules/*.md).
 *
 * .claude/rules is the single source of truth. Each source file may start with YAML
 * frontmatter containing a `paths:` list. The generated .mdc file gets:
 *   - `globs:` (comma-separated) and `alwaysApply: false` when `paths` is present
 *   - `alwaysApply: true` when it is absent
 *   - `description:` taken from the first `# ` heading in the body
 *
 * Usage:
 *   node scripts/sync-agent-rules.ts          write .cursor/rules
 *   node scripts/sync-agent-rules.ts --check  exit 1 if .cursor/rules is out of date
 *
 * Runs directly on Node 24+ (built-in TypeScript type stripping); no dependencies.
 */
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

const ROOT = process.cwd();
const SOURCE_DIR = join(ROOT, '.claude', 'rules');
const TARGET_DIR = join(ROOT, '.cursor', 'rules');
const HEADER = '<!-- GENERATED by scripts/sync-agent-rules.ts from .claude/rules. Do not edit. -->';

interface ParsedRule {
  readonly paths: ReadonlyArray<string>;
  readonly body: string;
}

async function listMarkdown(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await listMarkdown(full)));
    else if (entry.isFile() && entry.name.endsWith('.md')) files.push(full);
  }
  return files.sort();
}

function parseRule(text: string, file: string): ParsedRule {
  if (!text.startsWith('---\n')) return { paths: [], body: text.trim() };
  const end = text.indexOf('\n---', 4);
  if (end === -1) throw new Error(`${file}: unterminated frontmatter`);
  const front = text.slice(4, end).split('\n');
  const body = text.slice(end + 4).trim();
  const paths: string[] = [];
  let inPaths = false;
  for (const line of front) {
    if (/^paths:\s*$/.test(line)) {
      inPaths = true;
      continue;
    }
    const item = /^\s+-\s+["']?(.+?)["']?\s*$/.exec(line);
    if (inPaths && item?.[1] !== undefined) {
      paths.push(item[1]);
      continue;
    }
    if (line.trim() !== '') inPaths = false;
  }
  return { paths, body };
}

function describe(body: string, file: string): string {
  const heading = /^#\s+(.+)$/m.exec(body);
  if (heading?.[1] === undefined) throw new Error(`${file}: needs a "# Title" heading for the Cursor description`);
  return heading[1].replace(/"/g, "'");
}

function toMdc(rule: ParsedRule, file: string): string {
  const lines = ['---', `description: "${describe(rule.body, file)}"`];
  if (rule.paths.length > 0) {
    lines.push(`globs: ${rule.paths.join(',')}`, 'alwaysApply: false');
  } else {
    lines.push('alwaysApply: true');
  }
  lines.push('---', '', HEADER, '', rule.body, '');
  return lines.join('\n');
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const sources = await listMarkdown(SOURCE_DIR);
  const expected = new Map<string, string>();
  for (const src of sources) {
    const rel = relative(SOURCE_DIR, src).replace(/\.md$/, '.mdc');
    const text = await readFile(src, 'utf8');
    expected.set(join(TARGET_DIR, rel), toMdc(parseRule(text, src), src));
  }

  let existing: string[] = [];
  try {
    existing = (await listMarkdownLike(TARGET_DIR)).filter((f) => f.endsWith('.mdc'));
  } catch {
    existing = [];
  }

  const problems: string[] = [];
  for (const [target, content] of expected) {
    let current: string | undefined;
    try {
      current = await readFile(target, 'utf8');
    } catch {
      current = undefined;
    }
    if (current === content) continue;
    if (check) problems.push(`out of date: ${relative(ROOT, target)}`);
    else {
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, content, 'utf8');
      console.info(`wrote ${relative(ROOT, target)}`);
    }
  }
  for (const file of existing) {
    if (expected.has(file)) continue;
    if (check) problems.push(`orphaned (no source rule): ${relative(ROOT, file)}`);
    else {
      await rm(file);
      console.info(`removed ${relative(ROOT, file)}`);
    }
  }

  if (check && problems.length > 0) {
    console.error(`Cursor rules are out of sync with .claude/rules:\n  ${problems.join('\n  ')}\nRun: pnpm rules:sync`);
    process.exit(1);
  }
  if (check) console.info('Cursor rules are in sync.');
}

async function listMarkdownLike(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await listMarkdownLike(full)));
    else if (entry.isFile()) files.push(full);
  }
  return files.sort();
}

await main();
